#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "config/cpu8088.json"
VECTORS_PATH = ROOT / "tests/vectors/cpu8088_smoke.json"
STATE_PATH = ROOT / "src/cpu8088/state.inc"
SMOKE_PATH = ROOT / "src/cpu8088/smoke_vector.inc"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def validate_spec(spec: dict) -> None:
    expected_offset = 0
    for field in spec["state"]:
        if field["offset"] != expected_offset or field["width"] != 2:
            raise ValueError("8088 state fields must be contiguous 16-bit words")
        expected_offset += field["width"]

    claimed: dict[int, str] = {}
    for entry in spec["opcodes"]:
        if not 0 <= entry["first"] <= entry["last"] <= 0xFF:
            raise ValueError("opcode range is outside one byte")
        for opcode in range(entry["first"], entry["last"] + 1):
            if opcode in claimed:
                raise ValueError(f"opcode {opcode:#04x} has duplicate metadata")
            claimed[opcode] = entry["handler"]


def render_state(spec: dict) -> str:
    lines = [
        "; Generated by tools/generate_cpu8088.py from config/cpu8088.json.",
        "; Word register order follows the 8088 ModR/M register encoding.",
    ]
    for field in spec["state"]:
        lines.append(f"CPU_{field['name']:<5} = {field['offset']}")
    size = max(field["offset"] + field["width"] for field in spec["state"])
    lines.extend((f"CPU_STATE_SIZE = {size}", ""))
    for name, value in spec["flags"].items():
        lines.append(f"X86_FLAG_{name:<8} = ${value:04X}")
    lines.extend(("", "X86_FLAG_IF_HI = >X86_FLAG_IF", "X86_FLAG_DF_HI = >X86_FLAG_DF", ""))
    return "\n".join(lines)


def render_smoke(vectors: dict) -> str:
    vector = next(item for item in vectors["vectors"] if item["name"] == "native_smoke")
    program = bytes.fromhex(vector["program"])
    expected = vector["expected"]
    byte_list = ", ".join(f"${value:02X}" for value in program)
    return "\n".join((
        "; Generated by tools/generate_cpu8088.py from tests/vectors/cpu8088_smoke.json.",
        f"CPU_SMOKE_PROGRAM_SIZE = {len(program)}",
        f"CPU_SMOKE_SAVE_SIZE = {vector.get('preserveBytes', len(program))}",
        f"CPU_SMOKE_STEP_COUNT = {len(vector['statuses'])}",
        f"CPU_SMOKE_PENDING_IRQ = ${vector.get('pendingIrq', 0):02X}",
        f"CPU_SMOKE_EXPECTED_AX = ${expected['AX']:04X}",
        f"CPU_SMOKE_EXPECTED_CX = ${expected.get('CX', 0):04X}",
        f"CPU_SMOKE_EXPECTED_DX = ${expected.get('DX', 0):04X}",
        f"CPU_SMOKE_EXPECTED_BX = ${expected['BX']:04X}",
        f"CPU_SMOKE_EXPECTED_SP = ${expected.get('SP', 0):04X}",
        f"CPU_SMOKE_EXPECTED_SI = ${expected.get('SI', 0):04X}",
        f"CPU_SMOKE_EXPECTED_DI = ${expected.get('DI', 0):04X}",
        f"CPU_SMOKE_EXPECTED_ES = ${expected.get('ES', 0):04X}",
        f"CPU_SMOKE_EXPECTED_CS = ${expected.get('CS', 0):04X}",
        f"CPU_SMOKE_EXPECTED_SS = ${expected.get('SS', 0):04X}",
        f"CPU_SMOKE_EXPECTED_DS = ${expected.get('DS', 0):04X}",
        f"CPU_SMOKE_EXPECTED_FLAGS = ${expected['FLAGS']:04X}",
        "cpu_smoke_program:",
        f"    .byte {byte_list}",
        "",
    ))


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise ValueError(f"generated file is stale: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate shared 8088 CPU contracts")
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    spec = load_json(SPEC_PATH)
    vectors = load_json(VECTORS_PATH)
    validate_spec(spec)
    write_or_check(STATE_PATH, render_state(spec), args.check)
    write_or_check(SMOKE_PATH, render_smoke(vectors), args.check)
    if not args.check:
        print("Generated 8088 state layout and native smoke vector")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
